import { 
  Activity,
  BarChart2,
  BarChart3, 
  Box, 
  Briefcase, 
  Building2, 
  CheckSquare, 
  Coins,
  Contact, 
  CreditCard, 
  FileEdit,
  FileText, 
  Globe,
  Hash,
  Headphones, 
  History,
  Home, 
  Info,
  Key,
  Layers,
  LayoutDashboard, 
  Mail,
  Package, 
  Percent,
  PieChart, 
  Receipt, 
  Settings, 
  Shield,
  ShoppingBag,
  ShoppingCart, 
  Target, 
  Ticket, 
  UserCircle, 
  Users, 
  Wallet 
} from "lucide-react";

export const SIDEBAR_MENU = [
  {
    title: "Dashboard",
    icon: LayoutDashboard,
    path: "/dashboard",
  },
  {
    title: "CRM",
    icon: Users,
    items: [
      { title: "Dashboard", path: "/crm/dashboard", icon: LayoutDashboard },
      { title: "Todos", path: "/crm/todos", icon: CheckSquare },
      { title: "Todo Groups", path: "/crm/todo-groups", icon: Layers },
      { title: "Users", path: "/crm/users", icon: Users },
      { title: "Departments", path: "/crm/departments", icon: Building2 },
      { title: "Customers", path: "/crm/customers", icon: UserCircle },
      { title: "Contacts", path: "/crm/contacts", icon: Contact },
    ],
  },
  {
    title: "SALES",
    icon: Target,
    items: [
      { title: "Dashboard", path: "/sales/dashboard", icon: BarChart3 },
      { title: "Leads", path: "/sales/leads", icon: Target },
      { title: "Pipeline", path: "/sales/pipeline", icon: Activity },
      { title: "Forecast", path: "/sales/forecast", icon: BarChart2 },
      { title: "Quotations", path: "/sales/quotations", icon: FileText },
      { title: "Orders", path: "/sales/orders", icon: ShoppingCart },
      { title: "Invoices", path: "/sales/invoices", icon: Receipt },
      { title: "Payments", path: "/sales/payments", icon: Wallet },
    ],
  },
  {
    title: "PURCHASE",
    icon: ShoppingBag,
    items: [
      { title: "Dashboard", path: "/purchase/dashboard", icon: LayoutDashboard },
      { title: "Vendors", path: "/purchase/vendors", icon: Building2 },
      { title: "Purchase Orders", path: "/purchase/orders", icon: FileText },
      { title: "Bills", path: "/purchase/bills", icon: Receipt },
    ],
  },
  {
    title: "INVENTORY",
    icon: Package,
    items: [
      { title: "Dashboard", path: "/inventory/dashboard", icon: LayoutDashboard },
      { title: "Products", path: "/inventory/products", icon: Box },
      { title: "Categories", path: "/inventory/categories", icon: Package },
      { title: "Stock", path: "/inventory/stock", icon: PieChart },
    ],
  },
  {
    title: "SUPPORT",
    icon: Headphones,
    items: [
      { title: "Dashboard", path: "/support/dashboard", icon: LayoutDashboard },
      { title: "Tickets", path: "/support/tickets", icon: Ticket },
      { title: "Categories", path: "/support/categories", icon: LayoutDashboard },
    ],
  },
  {
    title: "FINANCE",
    icon: CreditCard,
    items: [
      { title: "Dashboard", path: "/finance/dashboard", icon: LayoutDashboard },
      { title: "Expenses", path: "/finance/expenses", icon: Wallet },
      { title: "Ledger", path: "/finance/ledger", icon: FileText },
      { title: "Categories", path: "/finance/categories", icon: Layers },
    ],
  },
  {
    title: "REPORTS",
    icon: BarChart2,
    items: [
      { title: "Sales Report", path: "/reports/sales", icon: BarChart2 },
      { title: "Purchase Report", path: "/reports/purchase", icon: BarChart3 },
      { title: "Stock Report", path: "/reports/stock", icon: Box },
      { title: "Finance Report", path: "/reports/finance", icon: PieChart },
    ],
  },
  {
    title: "SYSTEM",
    icon: Settings,
    items: [
      { title: "Roles", path: "/system/roles", icon: Shield },
      { title: "Permissions", path: "/system/permissions", icon: Key },
      { title: "Documentation", path: "/system/docs", icon: FileText },
      { 
        title: "Settings", 
        path: "/system/settings", 
        icon: Settings,
        subItems: [
          { title: "General", path: "/system/settings/general", icon: Settings },
          { title: "Email", path: "/system/settings/email", icon: Mail },
          { title: "Modules", path: "/system/settings/modules", icon: Layers },
          { title: "Currencies", path: "/system/settings/currencies", icon: Coins },
          { title: "Tax Rates", path: "/system/settings/tax-rates", icon: Percent },
          { title: "Email Templates", path: "/system/settings/templates", icon: FileEdit },
          { title: "Number Series", path: "/system/settings/number-series", icon: Hash },
          { title: "Audit Log", path: "/system/settings/audit-log", icon: History },
          { title: "System", path: "/system/settings/system-info", icon: Info },
        ]
      },
    ],
  },
];
